import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.7.1';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const supabase = createClient(
  Deno.env.get('SUPABASE_URL') ?? '',
  Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
);

interface ExportRequest {
  analysis_id: string;
  format: 'pdf' | 'csv';
  clerk_user_id: string;
}

// Generate PDF report using simple HTML string
async function generatePDFReport(analysis: any): Promise<Uint8Array> {
  try {
    // For now, create a simple text-based report since external PDF services may not work
    const reportContent = `
PhishNot Security Analysis Report
==================================

Analysis Date: ${new Date(analysis.analyzed_at).toLocaleString()}
Email From: ${analysis.sender_email || 'Unknown'}
Email Subject: ${analysis.subject || 'No subject'}

SECURITY RESULT: ${analysis.is_phishing ? 'PHISHING DETECTED' : 'EMAIL APPEARS SAFE'}
Confidence Score: ${analysis.confidence_score}%
Risk Level: ${analysis.is_phishing ? 'HIGH' : 'LOW'}

Analysis Details:
${analysis.analysis_reasons?.map((reason: string, i: number) => `${i + 1}. ${reason}`).join('\n') || 'No specific analysis details available'}

Security Recommendations:
${analysis.is_phishing ? `
⚠️  SECURITY ALERT - This email has been identified as a phishing attempt:
• DO NOT click any links in this email
• DO NOT provide personal or financial information
• DO NOT download any attachments
• Report this email to your IT security team
• Delete this email after reporting
• Be cautious of similar emails in the future
` : `
✅  This email appears to be legitimate based on our analysis:
• Always verify sender identity for sensitive requests
• Be cautious with links and attachments from unknown senders
• When in doubt, contact the sender through an independent channel
• Stay vigilant for social engineering attempts
`}

Generated by PhishNot Advanced Security Analysis
Report ID: ${analysis.id}
© ${new Date().getFullYear()} PhishNot Security

---
This report contains sensitive security information. Please handle accordingly.
    `;

    return new TextEncoder().encode(reportContent);
  } catch (error) {
    console.error('PDF generation error:', error);
    throw error;
  }
}

// Generate CSV report
function generateCSVReport(analysis: any): string {
  const headers = ['Date', 'Sender', 'Subject', 'Result', 'Confidence', 'Risk_Level', 'Reasons'];
  const row = [
    new Date(analysis.analyzed_at).toISOString(),
    `"${(analysis.sender_email || '').replace(/"/g, '""')}"`,
    `"${(analysis.subject || '').replace(/"/g, '""')}"`,
    analysis.is_phishing ? 'PHISHING' : 'SAFE',
    analysis.confidence_score,
    analysis.is_phishing ? 'HIGH' : 'LOW',
    `"${(analysis.analysis_reasons?.join('; ') || '').replace(/"/g, '""')}"`
  ];
  
  return headers.join(',') + '\n' + row.join(',');
}

// Create shareable report link
async function createShareableLink(analysisId: string): Promise<string> {
  try {
    // Generate unique share token
    const shareToken = crypto.randomUUID();
    
    const { error } = await supabase
      .from('shareable_reports')
      .insert({
        analysis_id: analysisId,
        share_token: shareToken,
        expires_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days
        is_active: true
      });

    if (error) {
      console.error('Error creating shareable link:', error);
      throw error;
    }

    return `${Deno.env.get('SUPABASE_URL')?.replace('supabase.co', 'supabase.co')}/functions/v1/shared-report/${shareToken}`;
  } catch (error) {
    console.error('Shareable link creation error:', error);
    throw error;
  }
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    console.log('Export request received:', req.method);
    
    const { analysis_id, format, clerk_user_id, action, custom_analysis }: ExportRequest & { action?: string; custom_analysis?: any } = await req.json();

    console.log('Export request data:', { analysis_id, format, action, has_custom_analysis: !!custom_analysis });

    if (!analysis_id || !clerk_user_id) {
      console.error('Missing required fields:', { analysis_id, clerk_user_id });
      return new Response(JSON.stringify({ error: 'Missing required fields' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    let analysis = custom_analysis;

    // If no custom analysis provided, get from database
    if (!analysis) {
      console.log('Fetching analysis from database...');
      const { data, error } = await supabase
        .from('email_analyses')
        .select('*')
        .eq('id', analysis_id)
        .eq('clerk_user_id', clerk_user_id)
        .single();

      if (error || !data) {
        console.error('Analysis not found or access denied:', error);
        return new Response(JSON.stringify({ error: 'Analysis not found or access denied' }), {
          status: 404,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        });
      }
      analysis = data;
    }

    console.log('Analysis data found:', { id: analysis.id, is_phishing: analysis.is_phishing });

    // Handle share link creation
    if (action === 'share') {
      console.log('Creating share link...');
      const shareUrl = await createShareableLink(analysis_id);
      console.log('Share link created:', shareUrl);
      return new Response(JSON.stringify({ shareUrl }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    // Handle export
    console.log('Starting export process for format:', format);
    
    if (format === 'pdf') {
      console.log('Generating PDF...');
      const pdfData = await generatePDFReport(analysis);
      console.log('PDF generated, size:', pdfData.length, 'bytes');
      
      return new Response(pdfData, {
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="phishnot-report-${analysis_id.substring(0, 8)}.pdf"`
        }
      });
    } else if (format === 'csv') {
      console.log('Generating CSV...');
      const csvData = generateCSVReport(analysis);
      console.log('CSV generated, length:', csvData.length);
      
      return new Response(csvData, {
        headers: {
          ...corsHeaders,
          'Content-Type': 'text/csv',
          'Content-Disposition': `attachment; filename="phishnot-report-${analysis_id.substring(0, 8)}.csv"`
        }
      });
    } else {
      console.error('Invalid format requested:', format);
      return new Response(JSON.stringify({ error: 'Invalid format. Use "pdf" or "csv"' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

  } catch (error) {
    console.error('Export error:', error);
    return new Response(JSON.stringify({ 
      error: 'Export failed', 
      details: error.message,
      stack: error.stack 
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});